name: Snyk Container Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-docker-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t secure-python-app:latest ./day2-docker-python

      - name: Run Snyk to scan Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: secure-python-app:latest
          args: --file=day2-docker-python/Dockerfile
