name: Snyk Container Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-container:
    name: Snyk Docker Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t secure-python-app .

      - name: Snyk scan on Docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: secure-python-app
          args: --severity-threshold=medium
