name: Snyk Python Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-scan:
    name: Snyk Scan for Python dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r day2-docker-python/requirements.txt

      - name: Run Snyk vulnerability test
        uses: snyk/actions/python@0.5.0
        with:
          args: test --file=day2-docker-python/requirements.txt --package-manager=pip --skip-unresolved
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
